from .apartments import ApartmentListCreateAPI, ApartmentRetrieveUpdateDestroyAPI
from .booking import BookingAPIList, BookingAPIRetrieveDestroy, BookingAPICreate, RetrieveUpdateBookingStatusAPIView, BookingAPIViewApartmentOwnerList
from .reviews import ReviewListCreateAPIView, ReviewRetrieveUpdateDestroyAPIView
