# Generated by Django 6.0.4 on 2026-04-07 14:09

import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterApartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('AP', 'Apartment'), ('HS', 'House'), ('ST', 'Studio'), ('RM', 'Room')], default='AP', max_length=2)),
                ('min_rent_duration', models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 months'), (6, '6 months'), (7, '7 months'), (8, '8 months'), (9, '9 months'), (10, '10 months'), (11, '11 months'), (12, '12 months'), (13, '13 months'), (14, '14 months'), (15, '15 months'), (16, '16 months'), (17, '17 months'), (18, '18 months'), (19, '19 months'), (20, '20 months'), (21, '21 months'), (22, '22 months'), (23, '23 months'), (24, '24 months'), (999, 'More than 24 months')], default=1)),
                ('max_rent_duration', models.IntegerField(blank=True, choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 months'), (6, '6 months'), (7, '7 months'), (8, '8 months'), (9, '9 months'), (10, '10 months'), (11, '11 months'), (12, '12 months'), (13, '13 months'), (14, '14 months'), (15, '15 months'), (16, '16 months'), (17, '17 months'), (18, '18 months'), (19, '19 months'), (20, '20 months'), (21, '21 months'), (22, '22 months'), (23, '23 months'), (24, '24 months'), (999, 'More than 24 months')], null=True)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=5)),
                ('max_residents', models.PositiveIntegerField(default=1)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('size_of_property', models.PositiveIntegerField(help_text='Size in m²')),
                ('heating', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('terrace', models.BooleanField(default=False)),
                ('pets', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('good_for_couples', models.BooleanField(default=False)),
                ('musical_instruments', models.BooleanField(default=False)),
                ('small_kids', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bed', 'Bed'), ('Crock', 'Crock'), ('Cupboard', 'Cupboard'), ('Dryer', 'Dryer'), ('Dishwasher', 'Dishwasher'), ('Air conditioning', 'Air conditioning'), ('Heating', 'Heating'), ('Wi-Fi', 'Wi-Fi'), ('Kitchen', 'Kitchen'), ('Washing machine', 'Washing machine'), ('TV', 'TV'), ('Balcony', 'Balcony'), ('Terrace', 'Terrace')], max_length=109)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='apartments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'apartments',
                'indexes': [models.Index(fields=['city'], name='apartments_city_7f2b76_idx'), models.Index(fields=['price_per_month'], name='apartments_price_p_6f8be5_idx'), models.Index(fields=['created_at'], name='apartments_created_9022f2_idx')],
            },
        ),
    ]
