# Generated by Django 6.0.4 on 2026-04-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerapartments',
            old_name='landlord',
            new_name='user',
        ),
    ]
