# Generated by Django 6.0.4 on 2026-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_rename_landlord_registerapartments_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'amenities',
            },
        ),
        migrations.RemoveField(
            model_name='registerapartments',
            name='amenities',
        ),
        migrations.AddField(
            model_name='registerapartments',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='apartments', to='housing.amenity'),
        ),
    ]
