# Generated by Django 6.0.4 on 2026-04-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_amenity_remove_registerapartments_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerapartments',
            name='price_per_month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='registerapartments',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
