# Generated by Django 6.0.4 on 2026-04-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_review_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerapartments',
            name='house_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
